<?php

acf_add_local_field_group(
	array(
		'key'                   => 'group_6204a221b1f36',
		'title'                 => 'سیلیکون - گزینه های پست تکی',
		'fields'                => array(
			array(
				'key'               => 'field_6204a233c690a',
				'label'             => 'تصویر روی کاور',
				'name'              => 'cover_image',
				'type'              => 'image',
				'instructions'      => 'تصویر کاوری را که می‌خواهید در تک پست خود نمایش دهید انتخاب کنید. اگر می‌خواهید متفاوت باشند، می‌توانید از این به جای پست کوچک استفاده کنید.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'full',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_6204a27fc690b',
				'label'             => 'دسته اصلی',
				'name'              => 'main_category',
				'type'              => 'taxonomy',
				'instructions'      => 'طبقه بندی را انتخاب کنید که می خواهید دسته اصلی باشد. در فیلدهای متا نمایش داده می شود که در غیر این صورت همه دسته ها را نمایش می دهد.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'taxonomy'          => 'category',
				'field_type'        => 'select',
				'allow_null'        => 0,
				'add_term'          => 0,
				'save_terms'        => 0,
				'load_terms'        => 0,
				'return_format'     => 'object',
				'multiple'          => 0,
			),
			array(
				'key'               => 'field_6204a2c3c690c',
				'label'             => 'پس زمینه دسته بندی اصلی',
				'name'              => 'main_category_bg',
				'type'              => 'select',
				'instructions'      => 'یک پس زمینه برای دسته اصلی انتخاب کنید. برای نمایش در شبکه وبلاگ و نمایش لیست با نوار کناری استفاده می شود.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'bg-primary'   => 'اولیه',
					'bg-secondary' => 'ثانوی',
					'bg-success'   => 'موفقیت',
					'bg-info'      => 'اطلاعات',
					'bg-warning'   => 'هشدار',
					'bg-danger'    => 'خطر',
					'bg-light'     => 'روشن',
					'bg-dark'      => 'تاریک',
				),
				'default_value'     => 'bg-secondary',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 0,
				'return_format'     => 'value',
				'ajax'              => 0,
				'placeholder'       => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
	)
);
